name: mindedge
description: MindEdge — AI-Powered Education Assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  rive: ^0.13.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.0.3
  file_picker: ^8.0.0
  dio: ^5.4.0
  image_picker: ^1.1.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  open_filex: ^4.7.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  markdown: ^7.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Icon_app.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/icon/
